export const INTERACTIVE_ELEMENTS = [
	'a',
	'button',
	'input',
	'select',
	'textarea',
	'details',
	'summary',
	'DBButton',
	'DBLink',
	'DBInput',
	'DBSelect',
	'DBTextarea',
	'DBCheckbox',
	'DBRadio',
	'DBSwitch',
	'DBNavigationItem',
	'DBTabItem',
	'DBTag'
];

export const COMPONENTS: Record<string, string> = {
	DBButton: 'DBButton',
	DBInput: 'DBInput',
	DBTextarea: 'DBTextarea',
	DBSelect: 'DBSelect',
	DBCustomSelect: 'DBCustomSelect',
	DBCheckbox: 'DBCheckbox',
	DBRadio: 'DBRadio',
	DBSwitch: 'DBSwitch',
	DBTooltip: 'DBTooltip',
	DBIcon: 'DBIcon',
	DBAccordion: 'DBAccordion',
	DBAccordionItem: 'DBAccordionItem',
	DBBadge: 'DBBadge',
	DBLink: 'DBLink',
	DBNotification: 'DBNotification',
	DBDrawer: 'DBDrawer',
	DBHeader: 'DBHeader',
	DBNavigationItem: 'DBNavigationItem',
	DBTag: 'DBTag',
	DBTabItem: 'DBTabItem'
};

export const MESSAGES = {
	BUTTON_TYPE_REQUIRED: 'DBButton must have an explicit type attribute (submit, button, or reset)',
	BUTTON_NO_TEXT_MISSING_ICON: 'DBButton with noText must have an icon prop',
	BUTTON_NO_TEXT_MISSING_TOOLTIP: 'DBButton with noText must have a DBTooltip child for accessibility',
	BUTTON_MULTIPLE_ICONS: 'DBButton can only use one of: icon, iconLeading, or iconTrailing',
	ACCORDION_NO_NESTED: 'DBAccordion must not be nested inside another DBAccordion as it confuses users',
	ACCORDION_ITEM_HEADLINE_REQUIRED: 'DBAccordionItem must have either headline or headlinePlain attribute',
	BADGE_CORNER_TEXT_TOO_LONG: 'DBBadge with corner placement must have max 3 characters in text/children',
	BADGE_CORNER_MISSING_LABEL: 'DBBadge with corner placement must have a label attribute for accessibility',
	BADGE_NO_INLINE_IN_INTERACTIVE: 'DBBadge inside {{parent}} cannot have placement="inline". Use corner placement instead',
	CLOSE_BUTTON_TEXT_REQUIRED: '{{component}} must have {{attribute}} attribute for accessibility',
	TEXT_OR_CHILDREN_REQUIRED: '{{component}} must have either a text property or children content',
	FORM_LABEL_REQUIRED: '{{component}} must have a label attribute for accessibility',
	FORM_VALIDATION_MESSAGE_REQUIRED: '{{component}} with {{attribute}} will use default browser validation message. Consider adding invalidMessage attribute for better UX',
	TAG_REMOVABLE_REMOVE_BUTTON_REQUIRED: 'DBTag with behavior="removable" must have removeButton attribute for accessibility',
	INPUT_TYPE_REQUIRED: 'DBInput should have type attribute for better developer experience',
	INPUT_FILE_MISSING_ACCEPT: 'DBInput with type="file" should have accept attribute',
	INPUT_INVALID_MULTIPLE: 'DBInput multiple attribute is only valid for type="file"',
	INPUT_INVALID_ACCEPT: 'DBInput accept attribute is only valid for type="file"',
	LINK_MISSING_TARGET_BLANK: 'DBLink with content="external" should have target="_blank"',
	LINK_MISSING_REFERRER_POLICY: 'DBLink with content="external" should have referrerPolicy attribute',
	LINK_MISSING_CONTENT_EXTERNAL: 'DBLink with target="_blank" should have content="external"',
	NAVIGATION_ITEM_MISSING_BACK_BUTTON_TEXT: 'DBNavigationItem must have backButtonText attribute for accessibility',
	SELECT_MISSING_OPTIONS: 'DBSelect must have either an options property or <option> children',
	CUSTOM_SELECT_MISSING_REMOVE_TAGS_TEXTS: 'DBCustomSelect with selectedType="tag" must have removeTagsTexts attribute for accessibility',
	HEADER_MISSING_BURGER_MENU_LABEL: 'DBHeader must have burgerMenuLabel attribute for accessibility',
	ICON_PREFER_ATTRIBUTE: 'Use icon attribute instead of DBIcon child in {{component}}'
};

export const MESSAGE_IDS = {
	BUTTON_TYPE_REQUIRED: 'missingType',
	BUTTON_NO_TEXT_MISSING_ICON: 'missingIcon',
	BUTTON_NO_TEXT_MISSING_TOOLTIP: 'missingTooltip',
	BUTTON_MULTIPLE_ICONS: 'multipleIcons',
	ACCORDION_NO_NESTED: 'noNested',
	ACCORDION_ITEM_HEADLINE_REQUIRED: 'headlineRequired',
	BADGE_CORNER_TEXT_TOO_LONG: 'textTooLong',
	BADGE_CORNER_MISSING_LABEL: 'missingLabel',
	BADGE_NO_INLINE_IN_INTERACTIVE: 'noInline',
	CLOSE_BUTTON_TEXT_REQUIRED: 'missingCloseButtonText',
	TEXT_OR_CHILDREN_REQUIRED: 'missingContent',
	FORM_LABEL_REQUIRED: 'missingLabel',
	FORM_VALIDATION_MESSAGE_REQUIRED: 'missingInvalidMessage',
	TAG_REMOVABLE_REMOVE_BUTTON_REQUIRED: 'missingRemoveButton',
	INPUT_TYPE_REQUIRED: 'missingType',
	INPUT_FILE_MISSING_ACCEPT: 'missingAccept',
	INPUT_INVALID_MULTIPLE: 'invalidMultiple',
	INPUT_INVALID_ACCEPT: 'invalidAccept',
	LINK_MISSING_TARGET_BLANK: 'missingTargetBlank',
	LINK_MISSING_REFERRER_POLICY: 'missingReferrerPolicy',
	LINK_MISSING_CONTENT_EXTERNAL: 'missingContentExternal',
	NAVIGATION_ITEM_MISSING_BACK_BUTTON_TEXT: 'missingBackButtonText',
	SELECT_MISSING_OPTIONS: 'missingOptions',
	CUSTOM_SELECT_MISSING_REMOVE_TAGS_TEXTS: 'missingRemoveTagsTexts',
	HEADER_MISSING_BURGER_MENU_LABEL: 'missingBurgerMenuLabel',
	ICON_PREFER_ATTRIBUTE: 'preferAttribute'
};
