packages:
  - "packages/*"
  - "output/*"
  - "showcases/*"
  - "storybooks/*"
  - "docs"
  - "scripts"
  - "figma-code-connect/*"

allowBuilds:
  "@compodoc/compodoc": false
  "@db-ux/db-theme": true
  "@db-ux/db-theme-fonts": true
  "@db-ux/db-theme-icons": true
  "@db-ux/db-theme-illustrative-icons": true
  "@parcel/watcher": false
  accessibility-checker: false
  chromedriver: false
  core-js: false
  esbuild: true
  ffmpeg-static: false
  lmdb: false
  msgpackr-extract: false
  puppeteer: true
  rs-module-lexer: false
  sharp: false
  svelte-preprocess: false
  ttf2woff2: false
  unrs-resolver: false

engineStrict: true

minimumReleaseAgeExclude:
  - marked@4.0.10

overrides:
  marked@<4.0.10: ^4.0.10

saveExact: true
