import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

/**
 * Regression test for the attribute-passing bug where iterating a live
 * NamedNodeMap by forward index while removing attributes causes skipped
 * entries. See: https://github.com/BuilderIO/mitosis/issues/XXXX
 *
 * Reproduction: <db-stack data-a="1" data-b="2"> only forwards one of the
 * two data-* attributes to the inner element because removing an attribute
 * shifts the live collection and the loop index skips the next item.
 *
 * This test exercises the generated `enableAttributePassing` code from the
 * Angular and Stencil outputs to assert ALL data-* and aria-* attributes are
 * forwarded, not just the ones that survive the index shift.
 */

/**
 * Minimal mock of a live NamedNodeMap — entries shift when an attribute is
 * removed, exactly like the real DOM `element.attributes`.
 */
class LiveAttributeMap {
	private attrs: { name: string; value: string }[] = [];

	get length() {
		return this.attrs.length;
	}

	item(index: number) {
		return this.attrs[index] ?? null;
	}

	getNamedItem(name: string) {
		return this.attrs.find((a) => a.name === name) ?? null;
	}

	setNamedItem(name: string, value: string) {
		const existing = this.attrs.find((a) => a.name === name);
		if (existing) {
			existing.value = value;
		} else {
			this.attrs.push({ name, value });
		}
	}

	removeNamedItem(name: string) {
		const idx = this.attrs.findIndex((a) => a.name === name);
		if (idx !== -1) this.attrs.splice(idx, 1);
	}
}

/** Minimal mock element with a live attribute map. */
function createElement(
	tag: string,
	attrs: Record<string, string> = {}
): {
	tagName: string;
	attributes: LiveAttributeMap;
	getAttribute: (name: string) => string | null;
	setAttribute: (name: string, value: string) => void;
	removeAttribute: (name: string) => void;
	closest: (selector: string) => any;
} {
	const map = new LiveAttributeMap();
	for (const [k, v] of Object.entries(attrs)) {
		map.setNamedItem(k, v);
	}

	const el: any = {
		tagName: tag.toUpperCase(),
		attributes: map,
		getAttribute(name: string) {
			return map.getNamedItem(name)?.value ?? null;
		},
		setAttribute(name: string, value: string) {
			map.setNamedItem(name, value);
		},
		removeAttribute(name: string) {
			map.removeNamedItem(name);
		},
		closest(_selector: string) {
			return null; // overridden per test
		}
	};
	return el;
}

/**
 * This is the exact `enableAttributePassing` logic as generated by the
 * current Mitosis version (extracted from the Angular/Stencil output).
 * It demonstrates the bug: forward iteration + removal = skipped attributes.
 */
function enableAttributePassingBuggy(
	element: ReturnType<typeof createElement> | null,
	parent: ReturnType<typeof createElement> | null
) {
	if (element && parent) {
		const attributes = parent.attributes;
		for (let i = 0; i < attributes.length; i++) {
			const attr = attributes.item(i);
			if (
				attr &&
				attr.name !== 'data-density' &&
				(attr.name.startsWith('data-') || attr.name.startsWith('aria-'))
			) {
				if (attr.value) {
					element.setAttribute(attr.name, attr.value);
				} else {
					element.removeAttribute(attr.name);
				}
				parent.removeAttribute(attr.name);
			} else if (attr && ['style'].includes(attr.name)) {
				element.setAttribute(attr.name, attr.value);
				parent.removeAttribute(attr.name);
			} else if (attr && attr.name === 'class') {
				const isWebComponent = attr.value.includes('hydrated');
				const value = attr.value.replace('hydrated', '').trim();
				const currentClass = element.getAttribute('class');
				element.setAttribute(
					attr.name,
					`${currentClass ? currentClass : ''}${value ? ` ${value}` : ''}`
				);
				if (isWebComponent) {
					parent.setAttribute('class', 'hydrated');
				} else {
					parent.removeAttribute(attr.name);
				}
			}
		}
	}
}

/**
 * Fixed version: iterates backwards so removal doesn't shift unvisited items,
 * or snapshots the attribute list before iterating.
 * This is what the Mitosis update should produce.
 */
function enableAttributePassingFixed(
	element: ReturnType<typeof createElement> | null,
	parent: ReturnType<typeof createElement> | null
) {
	if (element && parent) {
		const attributes = parent.attributes;
		// Fix: iterate backwards to avoid index shift on removal
		for (let i = attributes.length - 1; i >= 0; i--) {
			const attr = attributes.item(i);
			if (
				attr &&
				attr.name !== 'data-density' &&
				(attr.name.startsWith('data-') || attr.name.startsWith('aria-'))
			) {
				if (attr.value) {
					element.setAttribute(attr.name, attr.value);
				} else {
					element.removeAttribute(attr.name);
				}
				parent.removeAttribute(attr.name);
			} else if (attr && ['style'].includes(attr.name)) {
				element.setAttribute(attr.name, attr.value);
				parent.removeAttribute(attr.name);
			} else if (attr && attr.name === 'class') {
				const isWebComponent = attr.value.includes('hydrated');
				const value = attr.value.replace('hydrated', '').trim();
				const currentClass = element.getAttribute('class');
				element.setAttribute(
					attr.name,
					`${currentClass ? currentClass : ''}${value ? ` ${value}` : ''}`
				);
				if (isWebComponent) {
					parent.setAttribute('class', 'hydrated');
				} else {
					parent.removeAttribute('class');
				}
			}
		}
	}
}

describe('attribute-passing: multiple data-*/aria-* forwarding', () => {
	it('BUG: current Mitosis output skips attributes when removing during forward iteration', () => {
		const parent = createElement('db-stack', {
			'_nghost-abc': '',
			'data-a': '1',
			'data-b': '2'
		});
		const child = createElement('div', { class: 'db-stack' });

		enableAttributePassingBuggy(child, parent);

		// This assertion documents the bug: NOT all data-* attributes are
		// forwarded. With the buggy forward iteration, one attribute is skipped.
		const forwarded = [
			child.getAttribute('data-a'),
			child.getAttribute('data-b')
		].filter(Boolean);

		// Bug: only 1 of 2 attributes gets forwarded
		expect(forwarded.length).toBeLessThan(2);
	});

	it('EXPECTED: all data-* attributes are forwarded to the inner element', () => {
		const parent = createElement('db-stack', {
			'_nghost-abc': '',
			'data-a': '1',
			'data-b': '2'
		});
		const child = createElement('div', { class: 'db-stack' });

		enableAttributePassingFixed(child, parent);

		expect(child.getAttribute('data-a')).toBe('1');
		expect(child.getAttribute('data-b')).toBe('2');
		// Attributes must be removed from the parent (host element)
		expect(parent.getAttribute('data-a')).toBeNull();
		expect(parent.getAttribute('data-b')).toBeNull();
	});

	it('EXPECTED: all aria-* attributes are forwarded to the inner element', () => {
		const parent = createElement('db-stack', {
			'_nghost-abc': '',
			'aria-label': 'Stack label',
			'aria-describedby': 'desc-1',
			'aria-hidden': 'true'
		});
		const child = createElement('div', { class: 'db-stack' });

		enableAttributePassingFixed(child, parent);

		expect(child.getAttribute('aria-label')).toBe('Stack label');
		expect(child.getAttribute('aria-describedby')).toBe('desc-1');
		expect(child.getAttribute('aria-hidden')).toBe('true');
		expect(parent.getAttribute('aria-label')).toBeNull();
		expect(parent.getAttribute('aria-describedby')).toBeNull();
		expect(parent.getAttribute('aria-hidden')).toBeNull();
	});

	it('EXPECTED: data-density is NOT forwarded (excluded by design)', () => {
		const parent = createElement('db-stack', {
			'data-density': 'functional',
			'data-custom': 'value'
		});
		const child = createElement('div', { class: 'db-stack' });

		enableAttributePassingFixed(child, parent);

		expect(parent.getAttribute('data-density')).toBe('functional');
		expect(child.getAttribute('data-density')).toBeNull();
		expect(child.getAttribute('data-custom')).toBe('value');
	});

	it('EXPECTED: mixed attributes — only data-*/aria-* are forwarded, others stay', () => {
		const parent = createElement('db-stack', {
			'_nghost-abc': '',
			id: 'my-stack',
			'data-a': '1',
			'data-b': '2',
			'data-c': '3',
			'aria-label': 'test'
		});
		const child = createElement('div', { class: 'db-stack' });

		enableAttributePassingFixed(child, parent);

		// data-* and aria-* forwarded
		expect(child.getAttribute('data-a')).toBe('1');
		expect(child.getAttribute('data-b')).toBe('2');
		expect(child.getAttribute('data-c')).toBe('3');
		expect(child.getAttribute('aria-label')).toBe('test');
		// Non-data/aria attributes stay on parent
		expect(parent.getAttribute('_nghost-abc')).toBe('');
		expect(parent.getAttribute('id')).toBe('my-stack');
	});
});

describe('attribute-passing: generated output validation', () => {
	const angularOutputPath = path.resolve(
		__dirname,
		'../../../../../output/angular/src/components/stack/stack.ts'
	);
	const stencilOutputPath = path.resolve(
		__dirname,
		'../../../../../output/stencil/src/components/stack/stack.tsx'
	);

	it('Angular output forwards all data-* attributes (integration check)', () => {
		if (!fs.existsSync(angularOutputPath)) {
			// Skip if outputs haven't been built yet — CI will catch this
			return;
		}

		const code = fs.readFileSync(angularOutputPath, 'utf-8');

		// After Mitosis fix: the code should snapshot attributes before iterating
		// (e.g. Array.from or [...]) so removal from the live NamedNodeMap during
		// iteration doesn't skip entries.
		const hasUnsafeIteration =
			// Bug pattern: assigns parent.attributes directly (no Array.from/spread)
			// then removes from parent inside the loop
			/const attributes = parent\.attributes;/.test(code) &&
			/parent\.removeAttribute/.test(code);

		// This assertion FAILS with the old buggy output and PASSES after the fix.
		expect(
			hasUnsafeIteration,
			'enableAttributePassing must snapshot parent.attributes before iterating (use Array.from or spread)'
		).toBe(false);
	});

	it('Stencil output forwards all data-* attributes (integration check)', () => {
		if (!fs.existsSync(stencilOutputPath)) {
			return;
		}

		const code = fs.readFileSync(stencilOutputPath, 'utf-8');

		const hasUnsafeIteration =
			/const attributes = parent\.attributes;/.test(code) &&
			/parent\.removeAttribute/.test(code);

		expect(
			hasUnsafeIteration,
			'enableAttributePassing must snapshot parent.attributes before iterating (use Array.from or spread)'
		).toBe(false);
	});
});
