import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { type ToolResult, err, MAX_JSON_OUTPUT, truncate } from '../utils';
import { getManifest } from '../utils/manifest';

// ---------------------------------------------------------------------------
// Structured tokens loaded from prebuild-generated JSON
// ---------------------------------------------------------------------------

const TOKENS_JSON_PATH = join(
	import.meta.dirname,
	'../../assets/tokens/tokens.json'
);

/** In-memory cache for the parsed tokens JSON. */
let _tokensCache: Record<string, Record<string, unknown>> | null = null;

/**
 * Loads and caches the structured tokens.json generated by the prebuild step.
 * Falls back gracefully if the file doesn't exist (e.g. first CI run).
 */
async function loadTokensJson(): Promise<Record<
	string,
	Record<string, unknown>
> | null> {
	if (_tokensCache) return _tokensCache;
	try {
		const raw = await readFile(TOKENS_JSON_PATH, 'utf-8');
		_tokensCache = JSON.parse(raw) as Record<
			string,
			Record<string, unknown>
		>;
		return _tokensCache;
	} catch {
		return null;
	}
}

/**
 * Clears or overrides the tokens cache — useful for testing.
 * Pass an empty `{}` to disable JSON lookups (forces manifest fallback).
 * Pass `undefined` or call without arguments to clear the cache.
 */
export function resetTokensCache(
	override?: Record<string, Record<string, unknown>> | null
): void {
	_tokensCache = override ?? null;
}

// ---------------------------------------------------------------------------
// Tool Handlers
// ---------------------------------------------------------------------------

/** Returns all available design token categories. */
export async function handleListDesignTokenCategories(): Promise<ToolResult> {
	const manifest = await getManifest();
	const tokensJson = await loadTokensJson();

	// Merge categories from both manifest (SCSS-based) and tokens.json (compiled)
	const categories = [
		...new Set([
			...Object.keys(manifest.tokens),
			...(tokensJson ? Object.keys(tokensJson) : []),
			'elevation' // always advertise elevation
		])
	];

	return {
		content: [{ type: 'text', text: JSON.stringify(categories, null, 2) }]
	};
}

/**
 * Returns design tokens for a given category.
 *
 * Reads from the structured assets/tokens/tokens.json (generated by prebuild)
 * which contains concrete primitive values. Falls back to manifest SCSS for
 * categories not covered by the JSON (e.g. animation, transitions raw SCSS).
 */
export async function handleGetDesignTokens({
	category
}: {
	category: string;
}): Promise<ToolResult> {
	// --- Try structured JSON first ---
	const tokensJson = await loadTokensJson();
	if (tokensJson && tokensJson[category]) {
		const categoryData = tokensJson[category];
		const formatted = JSON.stringify(categoryData, null, 2);
		return {
			content: [
				{ type: 'text', text: truncate(formatted, MAX_JSON_OUTPUT) }
			]
		};
	}

	// --- Fallback to manifest SCSS for categories not in JSON ---
	const manifest = await getManifest();
	const source = manifest.tokens[category];
	if (!source) {
		const availableCategories = [
			...new Set([
				...Object.keys(manifest.tokens),
				...(tokensJson ? Object.keys(tokensJson) : [])
			])
		];
		return err(
			`Error: unknown category '${category}'. Available: ${availableCategories.join(', ')}`
		);
	}

	// Filter to lines containing CSS custom properties or SCSS variables
	const lines = source
		.split('\n')
		.filter((line) => /--db-|^\$db-/.test(line));
	return {
		content: [
			{
				type: 'text',
				text: truncate(
					lines.length > 0 ? lines.join('\n') : source,
					MAX_JSON_OUTPUT
				)
			}
		]
	};
}
