import { existsSync } from 'node:fs';
import { readFile, readdir } from 'node:fs/promises';
import { basename, extname, join } from 'node:path';
import { type ToolResult, err } from '../utils';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * Path to pre-optimised visual assets generated by the prebuild step.
 * Images are already downsampled (max 800×800 px, JPEG q75) —
 * NO image processing happens at runtime.
 */
const VISUALS_DIR = join(import.meta.dirname, '../../assets/visuals');

const SUPPORTED_EXTENSIONS = new Set(['.jpg', '.jpeg', '.png', '.webp']);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Returns the list of available visual names (without extension). */
async function listAvailableVisuals(): Promise<string[]> {
	if (!existsSync(VISUALS_DIR)) return [];
	const files = await readdir(VISUALS_DIR);
	return files
		.filter((f) => SUPPORTED_EXTENSIONS.has(extname(f).toLowerCase()))
		.map((f) => basename(f, extname(f)));
}

/** Resolves a visual name to its file path, or null if not found. */
function resolveVisualPath(name: string): string | null {
	for (const ext of SUPPORTED_EXTENSIONS) {
		const candidate = join(VISUALS_DIR, `${name}${ext}`);
		if (existsSync(candidate)) return candidate;
	}
	return null;
}

/** Maps file extension to MIME type. */
function mimeTypeForExt(filePath: string): string {
	const ext = extname(filePath).toLowerCase();
	switch (ext) {
		case '.jpg':
		case '.jpeg':
			return 'image/jpeg';
		case '.png':
			return 'image/png';
		case '.webp':
			return 'image/webp';
		default:
			return 'application/octet-stream';
	}
}

// ---------------------------------------------------------------------------
// Tool Handlers
// ---------------------------------------------------------------------------

/**
 * Lists all available visual reference names.
 */
export async function handleListVisuals(): Promise<ToolResult> {
	const visuals = await listAvailableVisuals();

	if (visuals.length === 0) {
		return {
			content: [
				{
					type: 'text',
					text: 'No visual references available. The assets/visuals/ directory is empty or missing.'
				}
			]
		};
	}

	return {
		content: [
			{
				type: 'text',
				text: JSON.stringify(visuals, null, 2)
			}
		]
	};
}

/**
 * MCP tool handler: `get_visual_reference`
 *
 * Returns a pre-optimised visual reference image (max 800×800 px, JPEG q75)
 * as a Base64-encoded MCP image block. Images are read from `assets/visuals/`
 * which is populated at build time by the prebuild step — NO image processing
 * or native dependencies (sharp) are needed at runtime.
 *
 * Use this tool when the LLM needs visual context for complex layouts,
 * z-index reasoning, or verifying visual hierarchies.
 */
export async function handleGetVisualReference({
	name
}: {
	name: string;
}): Promise<ToolResult> {
	const imagePath = resolveVisualPath(name);

	if (!imagePath) {
		const available = await listAvailableVisuals();
		return err(
			`No visual found for '${name}'. ` +
				(available.length > 0
					? `Available: ${available.join(', ')}`
					: 'No visuals are currently available.')
		);
	}

	try {
		const buffer = await readFile(imagePath);
		const data = buffer.toString('base64');
		const mimeType = mimeTypeForExt(imagePath);

		return {
			content: [
				{
					type: 'image' as const,
					data,
					mimeType
				},
				{
					type: 'text',
					text: `Visual reference for '${name}' (pre-optimised: max 800×800 px, JPEG q75).`
				}
			]
		};
	} catch (error: unknown) {
		const message = error instanceof Error ? error.message : String(error);
		return err(`Failed to read visual for '${name}': ${message}`);
	}
}
