import type { InputType } from 'storybook/internal/csf';

export const StorybookCustomSelectArgTypes: Record<string, InputType> = {
	options: { control: 'text' },
	label: { control: 'text' },
	placeholder: { control: 'text' },
	id: { control: 'text' },
	multiple: { control: 'text' },
	variant: { control: 'text' },
	value: { control: 'text' },
	showLabel: { control: 'boolean' },
	message: { control: 'text' },
	showMessage: { control: 'boolean' },
	icon: { control: 'text' },
	showIcon: { control: 'boolean' },
	validation: { control: 'text' },
	invalidMessage: { control: 'text' },
	required: { control: 'boolean' },
	showRequiredAsterisk: { control: 'boolean' },
	disabled: { control: 'boolean' },
	formFieldWidth: { control: 'text' },
	info: { control: 'text' },
	lineBreak: { control: 'text' },
	dropdownWidth: { control: 'text' },
	placement: { control: 'text' },
	selectedType: { control: 'text' },
	showNoResults: { control: 'boolean' },
	noResultsText: { control: 'text' },
	showLoading: { control: 'boolean' },
	loadingText: { control: 'text' },
	showSearch: { control: 'boolean' },
	showSelectAll: { control: 'boolean' },
	showClearSelection: { control: 'boolean' },
	removeTagsTexts: { control: 'text' },
	searchValue: { control: 'text' },
	selectedLabels: { control: 'text' },
	transformSelectedLabels: { control: 'text' },
	searchFilter: { control: 'text' }
};
