---
name: "NPM Cache Action"
description: "Initialize NPM Cache"
inputs:
  nodeModulesPath:
    description: "Path for node_modules"
    required: false
    default: "**/node_modules"
  packageLockPath:
    description: "Path for package-lock.json"
    required: false
    default: "**/package-lock.json"
  nodeVersion:
    description: "Node version"
    required: false
    default: "18"
runs:
  using: "composite"
  steps:
    - name: 🆙 Init Cache
      uses: actions/setup-node@v3
      id: "setup-node"
      with:
        node-version: ${{ inputs.nodeVersion }}
        cache: "npm"
        cache-dependency-path: "**/package-lock.json"

    - name: 🔢 Display node and npm version
      shell: bash
      run: |
        node --version
        npm --version

    - name: ⏬ NPM ci
      shell: bash
      if: steps.setup-node.outputs.cache-hit != 'true'
      run: npm ci
