---
name: "NPM Cache Action"
description: "Initialize NPM Cache"
inputs:
  nodeModulesPath:
    description: "Path for node_modules"
    required: false
    default: "**/node_modules"
  packageLockPath:
    description: "Path for package-lock.json"
    required: false
    default: "**/package-lock.json"
  nodeVersion:
    description: "Node version"
    required: false
runs:
  using: "composite"
  steps:
    - name: 🆙 Setup node
      # pick the Node version to use and install it
      # https://github.com/actions/setup-node
      uses: actions/setup-node@v4
      with:
        # If node-version and node-version-file are both provided the action will use version from node-version.
        node-version: ${{ inputs.nodeVersion }}
        node-version-file: ".nvmrc"

    - name: 🖼️ Display node and npm version
      shell: bash
      run: |
        node --version
        npm --version

    - name: 🆒 Init Cache
      uses: actions/cache@v4
      id: "cache"
      with:
        path: ${{ inputs.nodeModulesPath }}
        key: ${{ runner.os }}-node-${{ inputs.nodeVersion }}-${{ hashFiles(inputs.packageLockPath) }}
        restore-keys: |
          ${{ runner.os }}-node-${{ inputs.nodeVersion }}

    - name: 🎄🎸🥊 Log Cache Hit
      shell: bash
      env:
        HIT: ${{ steps.cache.outputs.cache-hit }}
      run: echo $HIT

    - name: ⏬ NPM ci
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        npm ci
