---
name: "NPM Cache Action"
description: "Initialize NPM Cache"
inputs:
  nodeModulesPath:
    description: "Path for node_modules"
    required: false
    default: "**/node_modules"
  packageLockPath:
    description: "Path for package-lock.json"
    required: false
    default: "**/package-lock.json"
  nodeVersion:
    description: "Node version"
    required: false
    default: "18"
outputs:
  cache-hit:
    description: "A boolean value to indicate an exact match was found for the primary key"
    value: ${{ steps.set-cache.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
    - name: Setup node equally to our local development version
      # pick the Node version to use and install it
      # https://github.com/actions/setup-node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.nodeVersion }}
        cache: "npm"

    - name: Display node and npm version
      shell: bash
      run: |
        node --version
        npm --version

    - name: ⏬ Init Cache
      uses: actions/cache@v3
      id: "cache"
      with:
        path: ${{ inputs.nodeModulesPath }}
        key: ${{ runner.os }}-node-${{ inputs.nodeVersion }}-${{ hashFiles(inputs.packageLockPath) }}
        restore-keys: |
          ${{ runner.os }}-node-${{ inputs.nodeVersion }}
          node-cache-${{ runner.os }}-npm-

    - name: 📥 Download deps default-npm-cache
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
