---
name: "NPM Cache Action"
description: "Initialize NPM Cache"
inputs:
  nodeModulesPath:
    description: "Path for node_modules"
    required: false
    default: "**/node_modules"
  packageLockPath:
    description: "Path for package-lock.json"
    required: false
    default: "**/package-lock.json"
outputs:
  cache-hit:
    description: "A boolean value to indicate an exact match was found for the primary key"
    value: ${{ steps.set-cache.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
    - name: 📥 Download deps default-npm-cache
      uses: bahmutov/npm-install@v1
      with:
        useRollingCache: true
