---
name: "Playwright Cache Action"
description: "Initialize Playwright Cache"
inputs:
  installDeps:
    description: "Force install dependencies for playwright on host system"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: 🔄 Init Cache Default
      uses: ./.github/actions/npm-cache

    - name: 🔢 Get installed Playwright version
      shell: bash
      id: playwright-version
      run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').dependencies['@playwright/test'].version)")" >> $GITHUB_ENV

    - name: 🆒 Cache playwright binaries
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: ⏬ Install Playwright with dependencies
      shell: bash
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps

    - name: ⏬ Install Playwright's dependencies
      shell: bash
      if: ${{ inputs.installDeps }} == 'true'
      run: npx playwright install-deps
