import type { InputType } from 'storybook/internal/csf';

export const StorybookTextareaArgTypes: Record<string, InputType> = {
	label: { control: 'text' },
	variant: { control: 'select', options: ['above', 'floating'] },
	value: { control: 'text' },
	showLabel: { control: 'boolean' },
	showMessage: { control: 'boolean' },
	message: { control: 'text' },
	disabled: { control: 'boolean' },
	readOnly: { control: 'boolean' },
	validation: { control: 'select', options: ['invalid', 'valid', 'no-validation'] },
	invalidMessage: { control: 'text' },
	validMessage: { control: 'text' },
	required: { control: 'boolean' },
	showRequiredAsterisk: { control: 'boolean' },
	rows: { control: 'number' },
	cols: { control: 'number' },
	showResizer: { control: 'boolean' },
	fieldSizing: { control: 'select', options: ['fixed', 'content'] },
	resize: { control: 'select', options: ['none', 'both', 'horizontal', 'vertical'] },
	spellCheck: { control: 'boolean' },
	wrap: { control: 'select', options: ['hard', 'soft', 'off'] },
	placeholder: { control: 'text' },
	name: { control: 'text' },
	form: { control: 'text' },
	ariaDescribedBy: { control: 'text' },
	minLength: { control: 'number' },
	maxLength: { control: 'number' },
	autocomplete: { control: 'text' },
	messageIcon: { control: 'text' },
	showMessage: { control: 'boolean' },
	id: { control: 'text' },
	autofocus: { control: 'boolean' }
};
