---
name: "Cancel Workflow"
description: "Cancel this workflow on failure"
inputs:
  token:
    description: "A Github PAT"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        gh api \
          --method POST \
          --header "Accept: application/vnd.github+json" \
          /repos/db-ux-design-system/core-web/actions/runs/${{ github.run_id }}/cancel
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
