version = 1

# A simple glob of all files in resources/img/
[[annotations]]
path = ["**/*-snapshot.yaml", "**/*-screenshot.png"]
SPDX-FileCopyrightText = "DB Systel GmbH"
SPDX-License-Identifier = "CC0-1.0"
