import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import type { Framework } from '../types.js';

const SERVER_DIR = resolve(import.meta.dirname, '..');

/**
 * Shape of the embedded manifest.json generated by build-manifest.ts.
 * Used as the data source when the server runs outside the monorepo.
 */
export type Manifest = {
	icons: string[];
	components: Record<
		string,
		{
			props: string | null;
			examples: string[];
			exampleCode: Record<Framework, Record<string, string>>;
		}
	>;
	tokens: Record<string, string>;
	docs: Record<string, string>;
};

let _manifest: Manifest | null = null;

/** Clears the in-memory manifest cache, forcing the next call to re-read the file. */
export function resetManifestCache() {
	_manifest = null;
}

/**
 * Loads and caches the embedded manifest.json from the server's build directory.
 * Subsequent calls return the cached instance without re-reading the file.
 *
 * @throws {Error} When manifest.json is missing or cannot be parsed.
 */
export async function getManifest(): Promise<Manifest> {
	if (_manifest) return _manifest;
	const manifestPath = join(SERVER_DIR, 'manifest.json');
	if (!existsSync(manifestPath)) {
		throw new Error(`manifest.json not found at ${manifestPath}`);
	}
	try {
		_manifest = JSON.parse(await readFile(manifestPath, 'utf-8')) as Manifest;
	} catch {
		throw new Error('Failed to parse manifest.json — file may be corrupt or incomplete.');
	}
	return _manifest;
}
