import manifestData from '../manifest.json' with { type: 'json' };
import type { Framework } from '../types.js';

/**
 * Shape of the embedded manifest.json generated by build-manifest.ts.
 * Used as the data source when the server runs outside the monorepo.
 */
export type Manifest = {
	icons: string[];
	components: Record<
		string,
		{
			props: string | null;
			examples: string[];
			exampleCode: Record<Framework, Record<string, string>>;
		}
	>;
	tokens: Record<string, string>;
	docs: Record<string, string>;
	migrationGuides: Record<string, string>;
};

let _manifest: Manifest | null = null;

/**
 * Clears the in-memory manifest cache.
 * In tests, pass a fake manifest object to override the static import.
 */
export function resetManifestCache(override?: Manifest) {
	_manifest = override ?? null;
}

/**
 * Returns the statically imported manifest data, cached after the first call.
 * esbuild embeds manifest.json directly into the bundle via the static import.
 */
export async function getManifest(): Promise<Manifest> {
	if (_manifest) return _manifest;
	_manifest = manifestData as Manifest;
	return _manifest;
}
