import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Framework } from '../types.js';

/**
 * Shape of the embedded manifest.json generated by build-manifest.ts.
 * Used as the data source when the server runs outside the monorepo.
 */
export type Manifest = {
	icons: string[];
	components: Record<
		string,
		{
			props: string | null;
			examples: string[];
			exampleCode: Record<Framework, Record<string, string>>;
		}
	>;
	tokens: Record<string, string>;
	docs: Record<string, string>;
	migrationGuides: Record<string, string>;
};

let _manifest: Manifest | null = null;

/**
 * Clears the in-memory manifest cache.
 * In tests, pass a fake manifest object to override the loaded data.
 */
export function resetManifestCache(override?: Manifest) {
	_manifest = override ?? null;
}

/**
 * Returns the manifest data, cached after the first call.
 * Reads manifest.json from disk only if the file exists.
 *
 * @throws {Error} When manifest.json does not exist.
 */
export async function getManifest(): Promise<Manifest> {
	if (_manifest) return _manifest;

	const manifestPath = join(import.meta.dirname, '..', 'manifest.json');
	if (!existsSync(manifestPath)) {
		throw new Error(
			`[DB UX MCP] manifest.json not found at ${manifestPath}. Run "npm run build" first.`
		);
	}

	const raw = readFileSync(manifestPath, 'utf-8');
	_manifest = JSON.parse(raw) as Manifest;
	return _manifest;
}
