#!/bin/sh
# shellcheck disable=SC1091
# shellcheck source=./_/husky.sh
. "$(dirname "$0")/_/husky.sh"

npx validate-branch-name
npm run scritps:check-commit-mail
npm run scritps:md-resolve-svg
npm run scritps:prettier-stage
npm run lint
