#!/usr/bin/env sh
# shellcheck disable=SC1091
# shellcheck source=./_/husky.sh
. "$(dirname -- "$0")/_/husky.sh"

npx validate-branch-name
node scripts/check-commit-mail.js
npx --no -- lint-staged --config ./.lintstagedrc.js
npm run lint:jscpd
