---
name: Build Power Apps

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build-power-apps:
    name: Build Power Apps
    runs-on: ubuntu-latest
    steps:
      - name: ⬇ Checkout repo
        uses: actions/checkout@v4

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: ⬇ Download foundations build
        uses: ./.github/actions/download-tar-artifact
        with:
          name: db-ui-foundations-build
          path: packages/foundations/build

      - name: ⬇ Download output
        uses: ./.github/actions/download-tar-artifact
        with:
          name: db-ui-output
          path: output

      - name: 🖨 Copy Power Apps
        run: npm run postbuild:02_components

      - name: 🔨 Build Power Apps
        env:
          VALID_SEMVER_VERSION: ${{ inputs.version }}
        run: |
          cd build-power-apps
          npm i
          STRIPED_VERSION=${VALID_SEMVER_VERSION%-*}
          npx replace-in-file 0.0.0 ${STRIPED_VERSION//-/.} **/ControlManifest.Input.xml
          cd DBUI
          npx replace-in-file 0.0.0 ${STRIPED_VERSION//-/.} src/Other/Solution.xml
          dotnet build --configuration Release

      - name: ⬆ Upload Power Apps zip
        uses: ./.github/actions/upload-tar-artifact
        with:
          name: db-ui-powerapps
          path: build-power-apps/DBUI

      - name: 💀 Killing me softly
        uses: ./.github/actions/cancel-workflow
        if: failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
