---
name: Build Components

on:
  workflow_call:

jobs:
  build-stencil-targets:
    name: Build Components
    runs-on: ubuntu-latest
    steps:
      - name: ⬇ Checkout repo
        uses: actions/checkout@v3

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: ⬇ Download foundations
        uses: ./.github/actions/download-tar-artifact
        with:
          name: db-ui-foundations
          path: packages/foundations

      - name: 🔨 Build Components
        run: npm run build --workspace=@db-ui/components

      - name: ⬆ Upload Components
        uses: ./.github/actions/upload-tar-artifact
        with:
          name: db-ui-components
          path: packages/components

      - name: 💀 Killing me softly
        uses: ./.github/actions/cancel-workflow
        if: failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
