---
name: Build Showcases

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      showcase:
        required: true
        type: string

jobs:
  build-showcases:
    name: Build Showcase ${{ inputs.showcase }}
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: 🔄 Init Cache
        uses: ./.github/actions/pnpm-cache
        env:
          ASSET_INIT_VECTOR: ${{ secrets.ASSET_INIT_VECTOR }}
          ASSET_PASSWORD: ${{ secrets.ASSET_PASSWORD }}

      - name: ⏬ Download foundations build
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: db-ux-foundations-build
          path: packages/foundations/build

      - name: ⏬ Download output
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: db-ux-output
          path: output

      - name: ⏬ Download components build
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: db-ux-components-build
          path: packages/components/build

      - name: ⏬ Download postcss-plugin build
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: db-ux-postcss-plugin-build
          path: packages/postcss-plugin/build

      - name: 🔨 Build ${{ inputs.showcase }}
        env:
          ASSET_INIT_VECTOR: ${{ secrets.ASSET_INIT_VECTOR }}
          ASSET_PASSWORD: ${{ secrets.ASSET_PASSWORD }}
        run: pnpm --filter ${{ inputs.showcase }} run build

      - name: ⏫ Upload ${{ inputs.showcase }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: db-ux-${{ inputs.showcase }}
          path: build-showcases/${{ inputs.showcase }}
