---
name: Build Power Apps

on:
  workflow_call:

jobs:
  build-showcases:
    name: Build Power Apps
    runs-on: ubuntu-latest
    steps:
      - name: ⬇ Checkout repo
        uses: actions/checkout@v3

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: ⬇ Download Packages
        uses: ./.github/actions/download-tar-artifact
        with:
          name: db-ui-packages
          path: packages

      - name: 🖨 Copy Power Apps
        run: npm run copy:power-apps

      - name: 🔨 Build Power Apps
        run: |
          cd build-power-apps
          npm i
          cd DBUI
          msbuild /p:configuration=Release /t:build /restore

      - name: ⬆ Upload Power Apps zip
        uses: ./.github/actions/upload-tar-artifact
        with:
          name: db-ui-powerapps
          path: build-power-apps/DBUI

      - name: 💀 Killing me softly
        uses: ./.github/actions/cancel-workflow
        if: failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
