name: 🎭 Init Playwright

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  init-playwright:
    name: 🎭 Init Playwright - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, macos-14]
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: 🔄 Init Cache Default
        uses: ./.github/actions/pnpm-cache
        env:
          ASSET_INIT_VECTOR: ${{ secrets.ASSET_INIT_VECTOR }}
          ASSET_PASSWORD: ${{ secrets.ASSET_PASSWORD }}

      - name: 🔄 Init Playwright Cache
        uses: ./.github/actions/playwright-cache
        with:
          os: ${{ matrix.os }}
          version: ${{ inputs.version }}
