name: 🎭 Playwright E2E

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      baseUrl:
        required: false
        type: string

permissions:
  actions: write
  contents: write

jobs:
  playwright-patternhub:
    name: 🧪🎭 - patternhub
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@v6

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: 🔄 Init Playwright Cache
        uses: ./.github/actions/playwright-cache
        with:
          os: ubuntu-24.04
          version: ${{ inputs.version }}

      - name: ⏬ Download foundations build
        uses: actions/download-artifact@v8
        with:
          name: db-ux-foundations-build
          path: packages/foundations/build

      - name: ⏬ Download output
        uses: actions/download-artifact@v8
        with:
          name: db-ux-output
          path: output

      - name: ⏬ Download components styles build
        uses: actions/download-artifact@v8
        with:
          name: db-ux-components-build
          path: packages/components/build

      - name: ⏬ Download patternhub
        uses: actions/download-artifact@v8
        with:
          name: db-ux-patternhub
          path: build-showcases/patternhub

      # We test everything for patternhub and main branch
      - name: 👩‍🔬 Test showcase with Playwright 🎭
        shell: bash
        env:
          NEXT_PUBLIC_BASE_PATH: ${{ inputs.baseUrl }}
        run: |
          mkdir -p ./build-showcases${{ inputs.baseUrl }}
          cp -RT ./build-showcases/patternhub ./build-showcases${{ inputs.baseUrl }}
          npm run test:e2e --workspace=patternhub

      - name: 🔣 Print GitHub Report
        if: failure()
        shell: bash
        run: |
          npx playwright merge-reports --reporter github ./blob-report

      - name: 🆙 Upload test results
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: patternhub-playwright-results
          path: ./showcases/patternhub/test-results
          retention-days: 30
