name: Commit Regenerated Snapshots

on:
  workflow_call:
    inputs:
      components:
        description: "Regenerate snapshots for components"
        required: true
        type: boolean
      foundations:
        description: "Regenerate snapshots for foundations"
        required: true
        type: boolean
      patternhub:
        description: "Regenerate snapshots for patternhub"
        required: true
        type: boolean
      showcases:
        description: "Regenerate snapshots for showcases"
        required: true
        type: boolean

jobs:
  commit-showcases:
    name: 🆙 Commit regenerated snapshots
    if: (inputs.showcases || inputs.components || inputs.foundations || inputs.patternhub) && !contains(github.actor,'[bot]')
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.head_ref }}

      - name: ⏬ Download components
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        # Only download artifact if the artifact exists
        if: inputs.components
        with:
          name: snapshots-components
          path: ./__snapshots__/

      - name: ⏬ Download foundations
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        # Only download artifact if the artifact exists
        if: inputs.foundations
        with:
          name: snapshots-foundations
          path: ./__snapshots__/foundations

      - name: ⏬ Download patternhub
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        if: inputs.patternhub
        with:
          name: snapshots-patternhub
          path: ./__snapshots__/

      - name: ⏬ Download showcase
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        if: inputs.showcases
        with:
          name: snapshots-showcases
          path: ./__snapshots__/

      - name: 🚘 Auto commit
        uses: ./.github/actions/auto-commit
        with:
          branch-name: "${{ github.head_ref }}-auto"
          commit-message: "auto update snapshots"
          commit-files: "__snapshots__/*"
          gh-token: ${{ secrets.GITHUB_TOKEN }}
