---
name: Publish all Packages to Registries

on:
  workflow_call:
    inputs:
      release:
        required: false
        default: "false"
        type: string
      preRelease:
        required: false
        default: "false"
        type: string
      version:
        required: true
        type: string

jobs:
  publish:
    name: Publish (or dry-run) latest package versions to npmjs.com registry
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    permissions:
      id-token: write
      contents: write
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: 🔄 Init Cache
        uses: ./.github/actions/pnpm-cache
        env:
          ASSET_INIT_VECTOR: ${{ secrets.ASSET_INIT_VECTOR }}
          ASSET_PASSWORD: ${{ secrets.ASSET_PASSWORD }}

      - name: ⏬ Download outputs
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: db-ux-outputs
          path: build-outputs

      - name: 📰 Dry Run PNPM Pack
        if: ${{ github.event_name != 'release' }}
        run: |
          pnpm pack --recursive --filter "@db-ux/*" --config.ignore-scripts=true --dry-run --json

      - name: 📰 Publish to NPM Registries
        if: ${{ github.event_name == 'release' }}
        run: |
          node scripts/github/publish-npm.js
        env:
          RELEASE: ${{ inputs.release }}
          PRE_RELEASE: ${{ inputs.preRelease }}
          VALID_SEMVER_VERSION: ${{ inputs.version }}
