name: "Close stale issues and PRs"
on:
  schedule:
    - cron: "30 1 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: "This issue is inactive for 30 days. It will be closed in 5 days without any activity."
          stale-pr-message: "This PR is inactive for 30 days. It will be closed in 5 days without any activity."
          days-before-stale: 30
          days-before-close: 5
